name: Manual Docker Build and Push

on:
  workflow_dispatch: # Allows manual triggering from the Actions tab
    inputs:
      image_name:
        description: 'Docker Hub image name (e.g., yourusername/your-repo)'
        required: true
        default: 'YOUR_DOCKERHUB_USERNAME/seedboxapi-py' # TODO: Change this!
      image_tag:
        description: 'Image tag (e.g., latest, v1.0.0)'
        required: true
        default: 'latest'
      dockerfile_path:
        description: 'Path to your Dockerfile'
        required: true
        default: './Dockerfile'

jobs:
  build-and-push-to-dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ github.event.inputs.dockerfile_path }}
          push: true
          tags: |
            ${{ github.event.inputs.image_name }}:${{ github.event.inputs.image_tag }}
            ${{ github.event.inputs.image_name }}:${{ github.sha }} # Also tag with the Git SHA for specific versioning
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max